services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: grandeonegai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   command: tunnel --url http://frontend:80
  #   restart: unless-stopped
  #   depends_on:
  #     - frontend

volumes:
  pgdata: